import type { Appointment } from "../../types/appointment";
import type { User } from "../../types/user";
import { Alert, Button, Divider, EmptyState } from "../../ui";
import { AppointmentStatusBadge } from "./AppointmentStatusBadge";
import { AgendaAppointmentCard } from "./AgendaAppointmentCard";
import { appointmentRules, formatDate, formatTime, sortByTime } from "./agenda";

type Props = { day: string; appointments: Appointment[]; detail: Appointment | null; showBack?: boolean; user: User; canAccessClinical: boolean; busy?: boolean; error?: string; onClose: () => void; onBack: () => void; onSelect: (item: Appointment) => void; onEdit: (item: Appointment) => void; onAttend: (item: Appointment) => void; onSetStatus: (item: Appointment, status: Appointment["status"]) => void; onDelete: (item: Appointment) => void; onAddAddendum: (item: Appointment) => void };
export function AgendaMonthPanel({ day, appointments, detail, showBack = true, user, canAccessClinical, busy, error, onClose, onBack, onSelect, onEdit, onAttend, onSetStatus, onDelete, onAddAddendum }: Props) {
  if (!detail) return <aside className="agenda-month-panel" aria-label="Citas del día"><header className="agenda-month-panel-header"><div><h2 className="atlas-section-title">Citas del día</h2><p className="atlas-muted">{formatDate(day)}</p></div><Button variant="ghost" aria-label="Cerrar panel del día" onClick={onClose}>×</Button></header><div className="agenda-month-panel-scroll">{appointments.length ? sortByTime(appointments).map((item) => <AgendaAppointmentCard appointment={item} variant="list" key={item.id} onSelect={onSelect} />) : <EmptyState title="No hay citas" description="No hay citas visibles para este día y los filtros actuales." />}</div></aside>;
  const rules = appointmentRules(detail, user); const active = detail.status === "scheduled" || detail.status === "confirmed";
  return <aside className="agenda-month-panel" aria-label="Detalle de cita"><header className="agenda-month-panel-header">{showBack && <Button variant="ghost" onClick={onBack}>← Citas del día</Button>}<Button variant="ghost" aria-label="Cerrar detalle de cita" onClick={onClose}>×</Button></header><div className="agenda-month-panel-scroll"><div className="agenda-drawer"><div className="agenda-drawer-title"><h2 className="atlas-section-title">Detalle de la cita</h2><AppointmentStatusBadge status={detail.status} /></div><dl className="agenda-details"><div><dt>Paciente</dt><dd>{detail.patient_name}</dd></div><div><dt>Fecha</dt><dd>{formatDate(detail.appointment_date)}</dd></div><div><dt>Hora</dt><dd>{formatTime(detail.appointment_time)}</dd></div><div><dt>Especialidad</dt><dd>{detail.specialty_name}</dd></div><div><dt>Centro</dt><dd>{detail.center_name || "No registrado"}</dd></div><div><dt>Médico responsable</dt><dd>{detail.doctor_name}</dd></div><div><dt>Motivo</dt><dd>{detail.reason || "Sin motivo registrado"}</dd></div><div><dt>Observaciones</dt><dd>{detail.notes || "Sin observaciones"}</dd></div></dl>{detail.has_clinical_history && <Alert title="Consulta clínica iniciada" tone="info">Las acciones y datos disponibles respetan el estado clínico actual.</Alert>}{detail.coverage_id && <Alert title="Cita bajo cobertura clínica" tone="info">{detail.original_doctor_name ? `Médico original: ${detail.original_doctor_name}.` : "La transferencia se registró en Atlas."}</Alert>}<Divider /><section aria-labelledby="agenda-month-actions"><h3 id="agenda-month-actions" className="atlas-card-title">Acciones</h3>{error && <Alert tone="danger" title="No se pudo realizar la acción">{error}</Alert>}<div className="agenda-drawer-actions">{!rules.completed && <Button variant="outline" disabled={busy} onClick={() => onEdit(detail)}>Editar cita</Button>}{active && detail.status !== "confirmed" && <Button variant="secondary" loading={busy} onClick={() => onSetStatus(detail, "confirmed")}>Confirmar</Button>}{active && !rules.scheduleLocked && <Button variant="outline" disabled={busy} onClick={() => onEdit(detail)}>Reprogramar</Button>}{rules.canCancel && <Button variant="danger" loading={busy} onClick={() => onSetStatus(detail, "cancelled")}>Cancelar</Button>}{rules.canCancel && <Button variant="outline" loading={busy} onClick={() => onSetStatus(detail, "no_show")}>Marcar No asistió</Button>}{canAccessClinical && rules.canAttend && <Button disabled={busy} onClick={() => onAttend(detail)}>Iniciar consulta</Button>}{rules.canDelete && <Button variant="danger" loading={busy} onClick={() => onDelete(detail)}>Eliminar cita</Button>}{rules.canAddAddendum && <Button disabled={busy} onClick={() => onAddAddendum(detail)}>Agregar nota adicional</Button>}</div></section></div></div></aside>;
}
