import type { Appointment } from "../../types/appointment";
import { Card, EmptyState } from "../../ui";
import { AppointmentStatusBadge } from "./AppointmentStatusBadge";
import { addDays, formatDate, formatTime, sortByTime, startOfWeek } from "./agenda";

function AppointmentCard({ appointment, onSelect }: { appointment: Appointment; onSelect: (appointment: Appointment) => void }) { return <button type="button" className="agenda-appointment-card" onClick={() => onSelect(appointment)} aria-label={`Ver cita de ${appointment.patient_name} a las ${formatTime(appointment.appointment_time)}`}><time className="agenda-appointment-time">{formatTime(appointment.appointment_time)}</time><span className="agenda-appointment-content"><strong>{appointment.patient_name}</strong><span>{appointment.reason || "Sin motivo registrado"}</span><span className="agenda-appointment-meta">{appointment.specialty_name} · {appointment.doctor_name}{appointment.center_name ? ` · ${appointment.center_name}` : ""}</span>{appointment.coverage_id && <span className="agenda-coverage">Cobertura{appointment.original_doctor_name ? ` · original: ${appointment.original_doctor_name}` : ""}</span>}</span><AppointmentStatusBadge status={appointment.status} /></button>; }
function NoAppointments({ description }: { description: string }) { return <EmptyState title="No hay citas para esta fecha" description={description} />; }
export function AgendaDayView({ appointments, date, onSelect }: { appointments: Appointment[]; date: string; onSelect: (appointment: Appointment) => void }) { return <section aria-labelledby="agenda-day-heading"><header className="agenda-view-heading"><div><h3 id="agenda-day-heading" className="atlas-section-title">{formatDate(date)}</h3><p className="atlas-muted">Eventos ordenados por hora registrada.</p></div><span className="atlas-help">{appointments.length} citas</span></header><Card className="agenda-events">{appointments.length ? sortByTime(appointments).map((appointment) => <AppointmentCard key={appointment.id} appointment={appointment} onSelect={onSelect} />) : <NoAppointments description="No hay citas para esta fecha dentro de tu alcance." />}</Card></section>; }
export function AgendaWeekView({ appointments, date, onSelect }: { appointments: Appointment[]; date: string; onSelect: (appointment: Appointment) => void }) { const start = startOfWeek(date); return <section aria-labelledby="agenda-week-heading"><header className="agenda-view-heading"><div><h3 id="agenda-week-heading" className="atlas-section-title">Semana del {formatDate(start, { day: "numeric", month: "short" })}</h3><p className="atlas-muted">Una sola carga para los siete días.</p></div></header><div className="agenda-week-grid">{Array.from({ length: 7 }, (_, index) => { const day = addDays(start, index); const entries = appointments.filter((item) => item.appointment_date === day); return <Card key={day} className="agenda-week-day"><h3>{formatDate(day, { weekday: "short", day: "numeric" })}</h3>{entries.length ? sortByTime(entries).map((item) => <AppointmentCard key={item.id} appointment={item} onSelect={onSelect} />) : <p className="atlas-help">Sin citas</p>}</Card>; })}</div></section>; }
export function AgendaDoctorsView({ appointments, onSelect }: { appointments: Appointment[]; onSelect: (appointment: Appointment) => void }) { const groups = new Map<string, Appointment[]>(); sortByTime(appointments).forEach((item) => groups.set(item.doctor_name, [...(groups.get(item.doctor_name) ?? []), item])); return <section aria-labelledby="agenda-doctors-heading"><header className="agenda-view-heading"><div><h3 id="agenda-doctors-heading" className="atlas-section-title">Citas por médico</h3><p className="atlas-muted">Distribución de citas visibles; no representa disponibilidad.</p></div></header>{groups.size ? <div className="agenda-doctors-grid">{[...groups].map(([doctor, entries]) => <Card key={doctor} className="agenda-doctor-group"><h3 className="atlas-card-title">{doctor}</h3>{entries.map((item) => <AppointmentCard key={item.id} appointment={item} onSelect={onSelect} />)}</Card>)}</div> : <Card><NoAppointments description="No hay citas dentro de los filtros seleccionados." /></Card>}</section>; }