import { after, afterEach, beforeEach, test } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "vite";
import { createBrowser } from "./browser.mjs";
const { dom } = createBrowser();
const { createElement: h, act } = await import("react"); const { createRoot } = await import("react-dom/client");
const server = await createServer({ server: { middlewareMode: true, ws: false }, appType: "custom", optimizeDeps: { noDiscovery: true, include: [] } });
const { default: Appointments } = await server.ssrLoadModule("/src/pages/Appointments.tsx"); const { api } = await server.ssrLoadModule("/src/services/api.ts");
const originalAdapter = api.defaults.adapter; const host = document.getElementById("root"); let root; let calls;
const appointment = { id: 8, patient_id: 6, doctor_id: 2, center_id: 1, specialty_id: 3, appointment_date: "2026-09-14", appointment_time: "08:30:00", reason: "Control", status: "scheduled", notes: "Nota", patient_name: "Ana Torres", patient_date_of_birth: "1988-01-01", doctor_name: "Dr. Osiris Valdés", center_name: "Centro Norte", center_city: "Santiago", specialty_name: "Medicina Interna", coverage_id: 4, original_doctor_id: 9, original_doctor_name: "Dra. Tania", has_clinical_history: false, clinical_history_id: null, clinical_history_status: null, clinical_history_doctor_id: null, created_at: "2026-01-01", updated_at: "2026-01-01" };
beforeEach(() => { root = createRoot(host); calls=[]; api.defaults.adapter=async(config)=>{ calls.push(config); if(config.url==="/appointments" && config.method==="put") return { data:appointment,status:200,statusText:"OK",headers:{},config}; const data=config.url==="/appointments"?[appointment]:config.url==="/appointments/scope-options"?{centers:[{id:1,name:"Centro Norte"}],doctors:[{id:2,full_name:"Dr. Osiris Valdés",center_ids:[1],specialties:[{id:3,name:"Medicina Interna"}]}]}:[]; return {data,status:200,statusText:"OK",headers:{},config}; }; });
afterEach(async()=>{ await act(async()=>root.unmount()); api.defaults.adapter=originalAdapter; }); after(async()=>{await server.close();dom.window.close();});
async function mount(roles){await act(async()=>{root.render(h(Appointments,{user:{id:2,full_name:"Usuario",email:"u@test",roles,is_active:true},onBack(){},canAccessClinical:roles.includes("doctor"),onAttendAppointment(){}})); await Promise.resolve();await Promise.resolve();});}
test("drawer muestra datos reales y cobertura",async()=>{await mount(["secretary"]);await act(async()=>host.querySelector(".agenda-appointment-card").click());assert.match(document.body.textContent,/Ana Torres/);assert.match(document.body.textContent,/Cita bajo cobertura clínica/);assert.doesNotMatch(document.body.textContent,/Iniciar consulta/);});
test("secretaría recibe acción Confirmar sin contenido clínico",async()=>{await mount(["secretary"]);await act(async()=>host.querySelector(".agenda-appointment-card").click());assert.ok([...document.body.querySelectorAll("button")].some(x=>x.textContent==="Confirmar"));assert.doesNotMatch(document.body.textContent,/Historia clínica|Diagnóstico|Receta/);});
test("vista semana y médicos reutilizan el mismo rango visible",async()=>{await mount(["secretary"]);await act(async()=>[...host.querySelectorAll("button")].find(x=>x.textContent==="Semana").click());assert.match(host.textContent,/Semana del/);await act(async()=>[...host.querySelectorAll("button")].find(x=>x.textContent==="Médicos").click());assert.match(host.textContent,/Citas por médico/);});
test("médico recibe acción clínica mientras admin puro no",async()=>{await mount(["doctor"]);await act(async()=>host.querySelector(".agenda-appointment-card").click());assert.match(document.body.textContent,/Iniciar consulta/);await act(async()=>root.unmount());root=createRoot(host);await mount(["admin"]);await act(async()=>host.querySelector(".agenda-appointment-card").click());assert.doesNotMatch(document.body.textContent,/Iniciar consulta/);});