import { after, afterEach, beforeEach, test } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "vite";
import { createBrowser } from "./browser.mjs";
import { clinicalHistoryInProgress, vitalSignsFixture } from "./fixtures/clinical.mjs";

const { dom } = createBrowser(); const { createElement: h, act } = await import("react"); const { createRoot } = await import("react-dom/client");
const server = await createServer({ server: { middlewareMode: true, ws: false }, appType: "custom", optimizeDeps: { noDiscovery: true, include: [] } });
const { default: AnamnesisModule } = await server.ssrLoadModule("/src/components/consultation/AnamnesisModule.tsx"); const { default: VitalSignsModule } = await server.ssrLoadModule("/src/components/consultation/VitalSignsModule.tsx"); const { api } = await server.ssrLoadModule("/src/services/api.ts"); const originalAdapter = api.defaults.adapter; const host = document.getElementById("root"); let root;
async function settle() { for (let index = 0; index < 3; index += 1) await act(async () => { await Promise.resolve(); }); }
function change(input, value) { Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(input, value); input.dispatchEvent(new dom.window.Event("input", { bubbles: true })); }
beforeEach(() => { root = createRoot(host); }); afterEach(async () => { await act(async () => root.unmount()); api.defaults.adapter = originalAdapter; }); after(async () => { await server.close(); dom.window.close(); });

test("anamnesis conserva edición local y entrega el formulario al guardado", async () => { let saved; await act(async () => root.render(h(AnamnesisModule, { episodeId: 81, appointmentReason: "Control", history: clinicalHistoryInProgress, completed: false, saving: false, onSave(form) { saved = form; } }))); const reason = [...host.querySelectorAll("input")][1]; await act(async () => change(reason, "Cambio local")); await act(async () => host.querySelector("button").click()); await settle(); assert.equal(reason.value, "Cambio local"); assert.equal(saved.reason_for_visit, "Cambio local"); });

test("anamnesis conserva edición ante rerender inocuo y cambia solo con episodio o revisión", async () => { const history = structuredClone(clinicalHistoryInProgress); const props = (episodeId, value) => ({ episodeId, appointmentReason: "Control", history: value, completed: false, saving: false, onSave() {} }); await act(async () => root.render(h(AnamnesisModule, props(81, history)))); const reason = [...host.querySelectorAll("input")][1]; await act(async () => change(reason, "Edición A")); await act(async () => root.render(h(AnamnesisModule, props(81, { ...history })))); assert.equal(reason.value, "Edición A"); const replacement = { ...history, id: 77, appointment_id: 82, revision: 1, reason_for_visit: "Consulta B" }; await act(async () => root.render(h(AnamnesisModule, props(82, replacement)))); await settle(); assert.equal(reason.value, "Consulta B"); });

test("anamnesis informa dirty contra la revisión guardada y vuelve a clean al adoptarla", async () => { const history = structuredClone(clinicalHistoryInProgress); const dirty = []; const props = value => ({ patientDateOfBirth: "1980-01-01", episodeId: 81, appointmentReason: "Control", history: value, completed: false, saving: false, onSave() {}, onDirtyChange(value) { dirty.push(value); } }); await act(async () => root.render(h(AnamnesisModule, props(history)))); await settle(); assert.equal(dirty.at(-1), false); const reason = [...host.querySelectorAll("input")][1]; await act(async () => change(reason, "Cambio pendiente")); await settle(); assert.equal(dirty.at(-1), true); await act(async () => root.render(h(AnamnesisModule, props({ ...history, revision: history.revision + 1, reason_for_visit: "Cambio pendiente" })))); await settle(); assert.equal(dirty.at(-1), false); });

test("anamnesis completed no ofrece mutación", async () => { await act(async () => root.render(h(AnamnesisModule, { episodeId: 81, appointmentReason: "Control", history: clinicalHistoryInProgress, completed: true, saving: false, onSave() { throw new Error("no debe guardar"); } }))); assert.equal(host.querySelector("button"), null); assert.equal(host.querySelector("input").disabled, true); });

test("vitales envía nulls y adopta el resultado canónico", async () => { let saved; let payload; api.defaults.adapter = async (config) => { payload = JSON.parse(config.data); return { data: { ...vitalSignsFixture, systolic_pressure: 121, updated_at: "2026-09-16T11:00:00" }, status: 200, statusText: "OK", headers: {}, config }; }; await act(async () => root.render(h(VitalSignsModule, { episodeId: 81, historyId: 42, vitalSigns: vitalSignsFixture, completed: false, loading: false, onSaved(value) { saved = value; } }))); const input = host.querySelector("input"); await act(async () => change(input, "121")); await act(async () => [...host.querySelectorAll("button")].at(-1).click()); await settle(); assert.equal(payload.systolic_pressure, 121); assert.equal(payload.temperature_c, null); assert.equal(saved.systolic_pressure, 121); });

test("vitales informa dirty, conserva el borrador ante error y limpia tras respuesta canónica", async () => { const dirty = []; let fail = true; let saved; api.defaults.adapter = async config => { if (fail) throw Object.assign(new Error("rechazado"), { response: { data: { detail: "Rechazado" } } }); saved = { ...vitalSignsFixture, systolic_pressure: 122, updated_at: "2026-09-16T11:00:00" }; return { data: saved, status: 200, statusText: "OK", headers: {}, config }; }; const props = value => ({ episodeId: 81, historyId: 42, vitalSigns: value, completed: false, loading: false, onSaved() {}, onDirtyChange(value) { dirty.push(value); } }); await act(async () => root.render(h(VitalSignsModule, props(vitalSignsFixture)))); await settle(); const input = host.querySelector("input"); await act(async () => change(input, "122")); await settle(); assert.equal(dirty.at(-1), true); await act(async () => [...host.querySelectorAll("button")].at(-1).click()); await settle(); assert.equal(input.value, "122"); assert.equal(dirty.at(-1), true); fail = false; await act(async () => [...host.querySelectorAll("button")].at(-1).click()); await settle(); await act(async () => root.render(h(VitalSignsModule, props(saved)))); await settle(); assert.equal(dirty.at(-1), false); });

test("vitales reemplaza el episodio y completed no permite mutación", async () => { const props = (episodeId, historyId, value, completed = false) => ({ episodeId, historyId, vitalSigns: value, completed, loading: false, onSaved() {} }); await act(async () => root.render(h(VitalSignsModule, props(81, 42, vitalSignsFixture)))); assert.equal(host.querySelector("input").value, "120"); await act(async () => root.render(h(VitalSignsModule, props(82, 77, null)))); await settle(); assert.equal(host.querySelector("input").value, ""); await act(async () => root.render(h(VitalSignsModule, props(82, 77, null, true)))); assert.equal([...host.querySelectorAll("button")].at(-1), undefined); assert.equal(host.querySelector("input").disabled, true); });
