import { useEffect, useState } from "react";
import { api } from "../services/api";
import type { Appointment, AppointmentInput } from "../types/appointment";
import type { Patient } from "../types/patient";

const empty: AppointmentInput = { patient_id: 0, appointment_date: new Date().toISOString().slice(0,10), appointment_time: "08:00", reason: "", status: "scheduled", notes: "" };
const labels: Record<string,string> = { scheduled:"Programada", confirmed:"Confirmada", completed:"Completada", cancelled:"Cancelada", no_show:"No asistió" };

export default function Appointments({ onBack }: { onBack: () => void }) {
  const [items,setItems]=useState<Appointment[]>([]); const [patients,setPatients]=useState<Patient[]>([]);
  const [form,setForm]=useState<AppointmentInput>(empty); const [editing,setEditing]=useState<Appointment|null>(null);
  const [showForm,setShowForm]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  async function load(){ setLoading(true); try { const [a,p]=await Promise.all([api.get<Appointment[]>("/appointments"),api.get<Patient[]>("/patients",{params:{limit:100}})]); setItems(a.data); setPatients(p.data); } catch(e:any){setError(e?.response?.data?.detail||"No fue posible cargar la agenda.")} finally{setLoading(false)} }
  useEffect(()=>{void load()},[]);
  function openNew(){setEditing(null);setForm({...empty});setShowForm(true)}
  function edit(a:Appointment){setEditing(a);setForm({patient_id:a.patient_id,appointment_date:a.appointment_date,appointment_time:a.appointment_time.slice(0,5),reason:a.reason||"",status:a.status,notes:a.notes||""});setShowForm(true)}
  async function save(){setError("");try{if(editing)await api.put(`/appointments/${editing.id}`,form);else await api.post("/appointments",form);setShowForm(false);await load()}catch(e:any){setError(e?.response?.data?.detail||"No fue posible guardar la cita.")}}
  async function remove(id:number){if(!confirm("¿Eliminar esta cita?"))return;try{await api.delete(`/appointments/${id}`);await load()}catch(e:any){setError(e?.response?.data?.detail||"No fue posible eliminar la cita.")}}
  return <section>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><button onClick={onBack} className="text-sm font-medium text-teal-700 hover:underline">← Volver al dashboard</button><h2 className="mt-2 text-2xl font-bold">Agenda de citas</h2><p className="mt-1 text-sm text-slate-500">Programa y administra las citas de los pacientes.</p></div><button onClick={openNew} className="rounded-lg bg-teal-700 px-4 py-2 font-medium text-white">+ Nueva cita</button></div>
    {error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="mt-6 overflow-hidden rounded-xl border bg-white shadow-sm">{loading?<p className="p-6 text-slate-500">Cargando agenda...</p>:items.length===0?<p className="p-10 text-center text-slate-500">No hay citas registradas.</p>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Fecha</th><th className="px-4 py-3">Hora</th><th className="px-4 py-3">Paciente</th><th className="px-4 py-3">Médico</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Motivo</th><th className="px-4 py-3 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(a=><tr key={a.id}><td className="px-4 py-3">{a.appointment_date}</td><td className="px-4 py-3 font-medium">{a.appointment_time.slice(0,5)}</td><td className="px-4 py-3 font-medium">{a.patient_name}</td><td className="px-4 py-3">{a.doctor_name}</td><td className="px-4 py-3">{labels[a.status]}</td><td className="px-4 py-3">{a.reason||"—"}</td><td className="px-4 py-3 text-right"><button onClick={()=>edit(a)} className="mr-3 font-medium text-teal-700">Editar</button><button onClick={()=>void remove(a.id)} className="font-medium text-red-700">Eliminar</button></td></tr>)}</tbody></table></div>}</div>
    {showForm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h3 className="text-xl font-bold">{editing?"Editar cita":"Nueva cita"}</h3><label className="mt-4 block text-sm font-medium">Paciente<select value={form.patient_id||""} onChange={e=>setForm({...form,patient_id:Number(e.target.value)})} className="mt-1 w-full rounded-lg border p-2.5" required><option value="">Seleccione...</option>{patients.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-medium">Fecha<input type="date" value={form.appointment_date} onChange={e=>setForm({...form,appointment_date:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5" required/></label><label className="text-sm font-medium">Hora<input type="time" value={form.appointment_time} onChange={e=>setForm({...form,appointment_time:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5" required/></label></div><label className="mt-4 block text-sm font-medium">Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as AppointmentInput["status"]})} className="mt-1 w-full rounded-lg border p-2.5">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-4 block text-sm font-medium">Motivo<input value={form.reason||""} onChange={e=>setForm({...form,reason:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="mt-4 block text-sm font-medium">Notas<textarea value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})} rows={3} className="mt-1 w-full rounded-lg border p-2.5"/></label><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setShowForm(false)} className="rounded-lg border px-5 py-2">Cancelar</button><button onClick={()=>void save()} className="rounded-lg bg-teal-700 px-5 py-2 font-medium text-white">Guardar</button></div></div></div>}
  </section>;
}
