import { useEffect, useState } from "react";
import { api } from "../services/api";

type Locality = { id:number; name:string; is_active:boolean };
type Center = { id:number; name:string; city:string; locality_id:number; locality?:Locality|null; center_type:string; address?:string|null; is_active:boolean };
type User = { id:number; full_name:string; email:string; roles:string[]; is_active:boolean };

export default function CareContext({ onBack }:{onBack:()=>void}) {
  const [localities,setLocalities]=useState<Locality[]>([]); const [centers,setCenters]=useState<Center[]>([]); const [users,setUsers]=useState<User[]>([]);
  const [localityName,setLocalityName]=useState(""); const [centerName,setCenterName]=useState(""); const [localityId,setLocalityId]=useState(""); const [centerType,setCenterType]=useState("consultorio"); const [error,setError]=useState("");
  async function load(){try{const [l,c,u]=await Promise.all([api.get<Locality[]>("/localities/all"),api.get<Center[]>("/centers"),api.get<User[]>("/users")]);setLocalities(l.data);setCenters(c.data);setUsers(u.data)}catch(e:any){setError(e?.response?.data?.detail||"No fue posible cargar la configuración.")}}
  useEffect(()=>{void load()},[]);
  async function addLocality(){if(!localityName.trim())return;try{await api.post("/localities",{name:localityName.trim(),is_active:true});setLocalityName("");await load()}catch(e:any){setError(e?.response?.data?.detail||"No fue posible crear la localidad.")}}
  async function addCenter(){if(!centerName.trim()||!localityId)return;try{await api.post("/centers",{name:centerName.trim(),center_type:centerType,locality_id:Number(localityId),address:null,is_active:true});setCenterName("");await load()}catch(e:any){setError(e?.response?.data?.detail||"No fue posible crear el centro.")}}
  async function assign(centerId:number,userId:number,isPrimary:boolean){try{await api.post(`/centers/${centerId}/users`,{user_id:userId,is_primary:isPrimary});await load()}catch(e:any){setError(e?.response?.data?.detail||"No fue posible asignar el usuario.")}}
  return <section><button onClick={onBack} className="text-sm font-medium text-teal-700 hover:underline">← Volver al dashboard</button><h2 className="mt-2 text-2xl font-bold">Localidades y centros</h2><p className="mt-1 text-sm text-slate-500">Configure localidades, centros y los lugares donde trabajan médicos y secretarias.</p>{error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Localidades</h3><div className="mt-4 flex gap-2"><input value={localityName} onChange={e=>setLocalityName(e.target.value)} placeholder="Ej. Higüey" className="flex-1 rounded-lg border p-2.5"/><button onClick={()=>void addLocality()} className="rounded-lg bg-teal-700 px-4 py-2 text-white">Agregar</button></div><div className="mt-4 space-y-2">{localities.map(l=><div key={l.id} className="flex justify-between rounded-lg bg-slate-50 p-3"><span>{l.name}</span><span className="text-xs text-slate-500">{l.is_active?"Activa":"Inactiva"}</span></div>)}</div></div>
      <div className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Nuevo centro</h3><input value={centerName} onChange={e=>setCenterName(e.target.value)} placeholder="Nombre del centro" className="mt-4 w-full rounded-lg border p-2.5"/><div className="mt-3 grid grid-cols-2 gap-3"><select value={localityId} onChange={e=>setLocalityId(e.target.value)} className="rounded-lg border p-2.5"><option value="">Localidad...</option>{localities.filter(l=>l.is_active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select value={centerType} onChange={e=>setCenterType(e.target.value)} className="rounded-lg border p-2.5"><option value="consultorio">Consultorio</option><option value="clinica">Clínica</option><option value="hospital">Hospital</option><option value="domicilio">Domicilio</option><option value="otro">Otro</option></select></div><button onClick={()=>void addCenter()} className="mt-3 rounded-lg bg-teal-700 px-4 py-2 text-white">Crear centro</button></div></div>
    <div className="mt-6 rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Asignación de usuarios</h3><div className="mt-4 space-y-4">{centers.map(c=><div key={c.id} className="rounded-lg border p-4"><div className="font-medium">{c.name} — {c.city}</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{users.filter(u=>u.roles.includes("doctor")||u.roles.includes("secretary")).map(u=><button key={u.id} onClick={()=>void assign(c.id,u.id,false)} className="rounded-lg border px-3 py-2 text-left text-sm hover:bg-slate-50"><span className="font-medium">{u.full_name}</span><span className="block text-xs text-slate-500">{u.roles.join(", ")} · asignar</span></button>)}</div></div>)}</div></div>
  </section>;
}
