import { useEffect, useMemo, useState } from "react";
import { api } from "../services/api";
import type { Appointment } from "../types/appointment";
import type { User } from "../types/user";

type Props = { user: User; onBack: () => void };
type Center = { id: number; name: string; city: string };
type Substitute = { id: number; full_name: string };
type Coverage = { id: number; principal_doctor_id: number; principal_doctor_name: string; substitute_doctor_id: number; substitute_doctor_name: string; center_id: number; center_name: string; starts_at: string; ends_at: string; revoked_at: string | null; status: "active" | "future" | "expired" | "revoked"; created_at: string };

const statusLabels = { active: "Activa", future: "Próxima", expired: "Expirada", revoked: "Revocada" };

export default function ClinicalCoverages({ user, onBack }: Props) {
  const [coverages, setCoverages] = useState<Coverage[]>([]); const [centers, setCenters] = useState<Center[]>([]); const [substitutes, setSubstitutes] = useState<Substitute[]>([]); const [appointments, setAppointments] = useState<Appointment[]>([]); const [centerId, setCenterId] = useState(0); const [substituteId, setSubstituteId] = useState(0); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { try { const [coverageResult, centerResult, appointmentResult] = await Promise.all([api.get<Coverage[]>("/clinical-coverages"), api.get<Center[]>("/centers/mine"), api.get<Appointment[]>("/appointments")]); setCoverages(coverageResult.data); setCenters(centerResult.data); setAppointments(appointmentResult.data); } catch (reason: any) { setError(reason?.response?.data?.detail || "No fue posible cargar las coberturas."); } }
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!centerId) { setSubstitutes([]); return; } void api.get<Substitute[]>("/clinical-coverages/eligible-substitutes", { params: { center_id: centerId } }).then(({ data }) => setSubstitutes(data)).catch((reason) => setError(reason?.response?.data?.detail || "No fue posible cargar suplentes.")); }, [centerId]);
  const outgoing = coverages.filter((item) => item.principal_doctor_id === user.id);
  const incoming = coverages.filter((item) => item.substitute_doctor_id === user.id);
  const transferableByCoverage = useMemo(() => new Map(outgoing.filter((item) => item.status === "active").map((coverage) => [coverage.id, appointments.filter((appointment) => { const at = new Date(`${appointment.appointment_date}T${appointment.appointment_time}`); return appointment.doctor_id === user.id && appointment.center_id === coverage.center_id && (appointment.status === "scheduled" || appointment.status === "confirmed") && !appointment.coverage_id && at >= new Date(coverage.starts_at) && at < new Date(coverage.ends_at); })])), [outgoing, appointments, user.id]);
  async function create() { if (!centerId || !substituteId || !startsAt || !endsAt) return; setSaving(true); setError(""); try { await api.post("/clinical-coverages", { center_id: centerId, substitute_doctor_id: substituteId, starts_at: startsAt, ends_at: endsAt }); setSubstituteId(0); await load(); } catch (reason: any) { setError(reason?.response?.data?.detail || "No fue posible crear la cobertura."); } finally { setSaving(false); } }
  async function revoke(id: number) { if (!confirm("¿Revocar esta cobertura clínica?")) return; try { await api.post(`/clinical-coverages/${id}/revoke`); await load(); } catch (reason: any) { setError(reason?.response?.data?.detail || "No fue posible revocar la cobertura."); } }
  async function transfer(coverageId: number, appointmentId: number) { if (!confirm("¿Transferir esta cita al médico suplente bajo la cobertura seleccionada?")) return; try { await api.post(`/clinical-coverages/${coverageId}/appointments/${appointmentId}/transfer`); await load(); } catch (reason: any) { setError(reason?.response?.data?.detail || "No fue posible transferir la cita."); } }
  return <section><button onClick={onBack} className="text-sm font-medium text-teal-700 hover:underline">← Volver al dashboard</button><h2 className="mt-2 text-2xl font-bold">Cobertura clínica</h2><p className="mt-1 text-sm text-slate-500">Autoriza temporalmente a otro médico y transfiere citas de forma explícita y auditable.</p>{error && <div role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Nueva cobertura</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm">Centro<select value={centerId} onChange={(e) => { setCenterId(Number(e.target.value)); setSubstituteId(0); }} className="mt-1 w-full rounded-lg border p-2.5"><option value={0}>Seleccione...</option>{centers.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.city}</option>)}</select></label><label className="text-sm">Médico suplente<select value={substituteId} onChange={(e) => setSubstituteId(Number(e.target.value))} className="mt-1 w-full rounded-lg border p-2.5" disabled={!centerId}><option value={0}>Seleccione...</option>{substitutes.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label className="text-sm">Desde<input type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="text-sm">Hasta<input type="datetime-local" value={endsAt} onChange={(e) => setEndsAt(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5" /></label></div><button onClick={() => void create()} disabled={saving || !centerId || !substituteId || !startsAt || !endsAt} className="mt-4 rounded-lg bg-teal-700 px-4 py-2 font-medium text-white disabled:opacity-40">{saving ? "Guardando..." : "Crear cobertura"}</button></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><CoverageList title="Coberturas que concedí" items={outgoing} transferableByCoverage={transferableByCoverage} onRevoke={revoke} onTransfer={transfer} /><CoverageList title="Coberturas recibidas" items={incoming} /></div></section>;
}

function CoverageList({ title, items, transferableByCoverage, onRevoke, onTransfer }: { title: string; items: Coverage[]; transferableByCoverage?: Map<number, Appointment[]>; onRevoke?: (id: number) => void; onTransfer?: (coverageId: number, appointmentId: number) => void }) { return <div className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">{title}</h3><div className="mt-4 space-y-3">{items.map((item) => <div key={item.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.principal_doctor_name} → {item.substitute_doctor_name}</p><p className="text-sm text-slate-600">{item.center_name}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.starts_at).toLocaleString()} — {new Date(item.ends_at).toLocaleString()}</p></div><span className="text-xs font-semibold">{statusLabels[item.status]}</span></div>{onRevoke && item.status !== "revoked" && <button onClick={() => onRevoke(item.id)} className="mt-3 text-sm font-medium text-red-700">{item.status === "expired" ? "Cerrar y restaurar citas pendientes" : "Revocar"}</button>}{transferableByCoverage?.get(item.id)?.map((appointment) => <div key={appointment.id} className="mt-3 flex items-center justify-between rounded bg-slate-50 p-2 text-sm"><span>Cita #{appointment.id} · {appointment.patient_name} · {appointment.appointment_date} {appointment.appointment_time.slice(0, 5)}</span><button onClick={() => onTransfer?.(item.id, appointment.id)} className="font-medium text-teal-700">Transferir por cobertura</button></div>)}</div>)}{!items.length && <p className="text-sm text-slate-500">No hay coberturas.</p>}</div></div>; }
