import { useEffect, useState } from "react";

import type { ClinicalHistory, ClinicalHistoryContent } from "../../types/clinical";

type Props = { episodeId: number; appointmentReason: string | null; history: ClinicalHistory | null; completed: boolean; saving: boolean; onSave: (form: ClinicalHistoryContent) => void | Promise<void> };
const emptyForm = (reason: string | null): ClinicalHistoryContent => ({ consultation_date: new Date().toISOString().slice(0, 10), reason_for_visit: reason || "", current_illness: "", personal_history: "", family_history: "", allergies: "", current_medications: "", previous_surgeries: "", chronic_conditions: "", habits: "", clinical_notes: "" });
const fromHistory = (history: ClinicalHistory): ClinicalHistoryContent => ({ consultation_date: history.consultation_date, reason_for_visit: history.reason_for_visit || "", current_illness: history.current_illness || "", personal_history: history.personal_history || "", family_history: history.family_history || "", allergies: history.allergies || "", current_medications: history.current_medications || "", previous_surgeries: history.previous_surgeries || "", chronic_conditions: history.chronic_conditions || "", habits: history.habits || "", clinical_notes: history.clinical_notes || "" });

export default function AnamnesisModule({ episodeId, appointmentReason, history, completed, saving, onSave }: Props) {
  const [form, setForm] = useState<ClinicalHistoryContent>(() => history ? fromHistory(history) : emptyForm(appointmentReason));
  useEffect(() => { setForm(history ? fromHistory(history) : emptyForm(appointmentReason)); }, [episodeId, history?.id, history?.revision, appointmentReason]);
  const update = (field: keyof ClinicalHistoryContent, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const field = (label: string, key: keyof ClinicalHistoryContent) => <label className="text-sm font-medium">{label}<textarea value={form[key] || ""} disabled={completed} onChange={(event) => update(key, event.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-2.5 disabled:bg-slate-100" /></label>;
  return <div className="rounded-xl border bg-white p-6 shadow-sm"><h3 className="text-lg font-semibold">Historia de la consulta</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Fecha de consulta<input type="date" value={form.consultation_date} disabled={completed} onChange={(event) => update("consultation_date", event.target.value)} className="mt-1 w-full rounded-lg border p-2.5 disabled:bg-slate-100" required /></label><label className="text-sm font-medium">Motivo de consulta<input value={form.reason_for_visit || ""} disabled={completed} onChange={(event) => update("reason_for_visit", event.target.value)} className="mt-1 w-full rounded-lg border p-2.5 disabled:bg-slate-100" /></label>{field("Enfermedad actual", "current_illness")}{field("Antecedentes personales", "personal_history")}{field("Antecedentes familiares", "family_history")}{field("Alergias", "allergies")}{field("Medicamentos actuales", "current_medications")}{field("Cirugías previas", "previous_surgeries")}{field("Enfermedades crónicas", "chronic_conditions")}{field("Hábitos", "habits")}</div><label className="mt-4 block text-sm font-medium">Notas clínicas<textarea value={form.clinical_notes || ""} disabled={completed} onChange={(event) => update("clinical_notes", event.target.value)} rows={5} className="mt-1 w-full rounded-lg border p-2.5 disabled:bg-slate-100" /></label>{!completed && <div className="mt-6 flex justify-end"><button onClick={() => void onSave(form)} disabled={saving} className="rounded-lg bg-teal-700 px-5 py-2.5 font-medium text-white disabled:opacity-50">{saving ? "Guardando..." : history ? "Actualizar consulta" : "Guardar consulta"}</button></div>}</div>;
}
