import { useEffect, useState } from "react";
import ClinicalOrdersSection from "../clinical/ClinicalOrdersSection";
import ConsultationHeader from "./ConsultationHeader";
import AnamnesisModule from "./AnamnesisModule";
import DiagnosesModule from "./DiagnosesModule";
import PrescriptionsModule from "./PrescriptionsModule";
import VitalSignsModule from "./VitalSignsModule";
import { api } from "../../services/api";
import { clinicalApi, clinicalErrorMessage } from "../../services/clinicalApi";
import { useConsultationBootstrap } from "../../hooks/useConsultationBootstrap";
import type { Appointment } from "../../types/appointment";
import type { ClinicalHistory, ClinicalHistoryContent, ConsultationContext, Diagnosis, MedicalStudy, Prescription, RequestedTest, VitalSigns } from "../../types/clinical";
import type { User } from "../../types/user";

type Props = { appointment: Appointment; onBack: () => void };
type PreviousDetails = { consultation: ClinicalHistory; vitalSigns: VitalSigns | null; diagnoses: Diagnosis[]; prescriptions: Prescription[]; requestedTests: RequestedTest[] };

export default function ConsultationWorkspace({ appointment, onBack }: Props) {
  const bootstrap = useConsultationBootstrap(appointment.id);
  const [context, setContext] = useState<ConsultationContext | null>(null); const [vitalSigns, setVitalSigns] = useState<VitalSigns | null>(null); const [diagnoses, setDiagnoses] = useState<Diagnosis[]>([]); const [prescriptions, setPrescriptions] = useState<Prescription[]>([]); const [requestedTests, setRequestedTests] = useState<RequestedTest[]>([]); const [requestedTest, setRequestedTest] = useState(""); const [studyCatalog, setStudyCatalog] = useState<MedicalStudy[]>([]); const [specialtyName, setSpecialtyName] = useState(""); const [saving, setSaving] = useState(false); const [completing, setCompleting] = useState(false); const [loadingVitalSigns, setLoadingVitalSigns] = useState(false); const [savingRequestedTest, setSavingRequestedTest] = useState(false); const [downloadingSummaryPdf, setDownloadingSummaryPdf] = useState(false); const [downloadingPrescriptionPdf, setDownloadingPrescriptionPdf] = useState(false); const [downloadingTestsPdf, setDownloadingTestsPdf] = useState(false); const [saved, setSaved] = useState<ClinicalHistory | null>(null); const [error, setError] = useState("");
  const [previousDetails, setPreviousDetails] = useState<PreviousDetails | null>(null);
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [loadingPrevious, setLoadingPrevious] = useState(false);
  const isCompleted = saved?.status === "completed";
  const previousConsultations = context?.previous_consultations.filter((item) => item.appointment_id !== context.appointment_id) || [];

  useEffect(() => { void api.get<User>("/auth/me").then(({ data }) => setCurrentUser(data)).catch(() => setCurrentUser(null)); }, []);
  useEffect(() => { setContext(null); setSaved(null); setDiagnoses([]); setPrescriptions([]); setRequestedTests([]); setVitalSigns(null); setLoadingVitalSigns(true); setStudyCatalog([]); setSpecialtyName(""); setError(""); }, [appointment.id, appointment.reason]);
  useEffect(() => { if (bootstrap.loading) return; if (bootstrap.error) { setError(bootstrap.error); return; } if (!bootstrap.context) return; setContext(bootstrap.context); setSaved(bootstrap.history); setDiagnoses(bootstrap.diagnoses); setPrescriptions(bootstrap.prescriptions); setRequestedTests(bootstrap.requestedTests); setVitalSigns(bootstrap.vitalSigns); setLoadingVitalSigns(false); setStudyCatalog(bootstrap.studyCatalog); setSpecialtyName(bootstrap.context.specialty_name); }, [bootstrap]);
  async function saveHistory(form: ClinicalHistoryContent) { if (!context || isCompleted) return; setSaving(true); setError(""); try { const data = saved ? await clinicalApi.updateHistory(saved.id, { ...form, expected_revision: saved.revision }) : await clinicalApi.createHistory(context.patient_id, { ...form, appointment_id: context.appointment_id }); setSaved(data); setContext((current) => current ? { ...current, previous_consultations: current.previous_consultations.some((item) => item.id === data.id) ? current.previous_consultations.map((item) => item.id === data.id ? data : item) : [data, ...current.previous_consultations] } : current); } catch (e: unknown) { setError(clinicalErrorMessage(e, "No fue posible guardar la consulta.")); } finally { setSaving(false); } }
  async function completeConsultation() { if (!saved || isCompleted || !window.confirm("¿Finalizar esta consulta? Después quedará en modo de solo lectura.")) return; setCompleting(true); setError(""); try { const data = await clinicalApi.completeHistory(saved.id); setSaved(data); setContext((current) => current ? { ...current, appointment_status: "completed", previous_consultations: current.previous_consultations.map((item) => item.id === data.id ? data : item) } : current); } catch (e: unknown) { setError(clinicalErrorMessage(e, "No fue posible finalizar la consulta.")); } finally { setCompleting(false); } }
  async function downloadPrescriptionPdf() { if (!saved || !prescriptions.length) return; setDownloadingPrescriptionPdf(true); setError(""); try { const blob = await clinicalApi.getPrescriptionPdf(saved.id); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `receta-${saved.id}.pdf`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (e: unknown) { setError(clinicalErrorMessage(e, "No fue posible generar la receta PDF.")); } finally { setDownloadingPrescriptionPdf(false); } }
  async function addRequestedTest(name = requestedTest) { const normalizedName = name.trim(); if (!saved?.id || isCompleted || !normalizedName) return; if (requestedTests.some((item) => item.test_name.toLocaleLowerCase() === normalizedName.toLocaleLowerCase())) { setError("El estudio o análisis ya está solicitado."); return; } setSavingRequestedTest(true); setError(""); try { const data = await clinicalApi.createRequestedTest(saved.id, { test_name: normalizedName }); setRequestedTests((current) => [...current, data]); setRequestedTest(""); } catch (e: unknown) { setError(clinicalErrorMessage(e, "No fue posible guardar el estudio solicitado.")); } finally { setSavingRequestedTest(false); } }
  async function removeRequestedTest(id: number) { if (isCompleted) return; try { await clinicalApi.deleteRequestedTest(id); setRequestedTests((current) => current.filter((item) => item.id !== id)); } catch (e: unknown) { setError(clinicalErrorMessage(e, "No fue posible eliminar el estudio solicitado.")); } }
  async function downloadRequestedTestsPdf() { if (!saved || !requestedTests.length) return; setDownloadingTestsPdf(true); setError(""); try { const response = await api.get<Blob>(`/clinical-history/${saved.id}/requested-tests/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `orden-estudios-${saved.id}.pdf`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (e: any) { setError(e?.response?.data?.detail || "No fue posible generar la orden PDF."); } finally { setDownloadingTestsPdf(false); } }
  async function downloadSummaryPdf() { if (!saved) return; setDownloadingSummaryPdf(true); setError(""); try { const response = await api.get<Blob>(`/clinical-history/${saved.id}/summary/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `resumen-consulta-${saved.id}.pdf`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (e: any) { setError(e?.response?.data?.detail || "No fue posible generar el resumen de consulta."); } finally { setDownloadingSummaryPdf(false); } }
  async function viewPrevious(consultation: ClinicalHistory) { setLoadingPrevious(true); setError(""); try { const [vitals, diagnosisList, prescriptionList, testList] = await Promise.all([api.get<VitalSigns | null>(`/clinical-history/${consultation.id}/vital-signs`), api.get<Diagnosis[]>(`/clinical-history/${consultation.id}/diagnoses`), api.get<Prescription[]>(`/clinical-history/${consultation.id}/prescriptions`), api.get<RequestedTest[]>(`/clinical-history/${consultation.id}/requested-tests`)]); setPreviousDetails({ consultation, vitalSigns: vitals.data, diagnoses: diagnosisList.data, prescriptions: prescriptionList.data, requestedTests: testList.data }); } catch (e: any) { setError(e?.response?.data?.detail || "No fue posible cargar el historial anterior."); } finally { setLoadingPrevious(false); } }
  async function downloadPreviousSummary(historyId: number) { setError(""); try { const response = await api.get<Blob>(`/clinical-history/${historyId}/summary/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `resumen-consulta-${historyId}.pdf`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (e: any) { setError(e?.response?.data?.detail || "No fue posible generar el resumen anterior."); } }

  if (bootstrap.loading) return <section><button onClick={onBack} className="text-sm font-medium text-teal-700 hover:underline">← Volver a la agenda</button><p className="mt-6 text-slate-500">Cargando contexto de atención...</p></section>;
  return <section><ConsultationHeader appointment={appointment} specialtyName={context?.specialty_name ?? appointment.specialty_name} onBack={onBack} />
    {error && <div role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{saved && <div className={`mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg p-3 text-sm ${isCompleted ? "bg-slate-200 text-slate-800" : "bg-emerald-50 text-emerald-800"}`}><span>{isCompleted ? "Consulta finalizada y bloqueada en modo de solo lectura." : "Consulta guardada correctamente."} ID #{saved.id} · cita #{saved.appointment_id}.</span><div className="flex flex-wrap gap-2"><button onClick={() => void downloadSummaryPdf()} disabled={downloadingSummaryPdf} className="rounded-lg border border-emerald-300 bg-white px-3 py-2 font-medium text-emerald-800 disabled:opacity-40">{downloadingSummaryPdf ? "Generando resumen..." : "Descargar resumen PDF"}</button>{!isCompleted && <button onClick={() => void completeConsultation()} disabled={completing || saving} className="rounded-lg bg-slate-900 px-3 py-2 font-medium text-white disabled:opacity-40">{completing ? "Finalizando..." : "Finalizar consulta"}</button>}</div></div>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-6">
      <AnamnesisModule episodeId={appointment.id} appointmentReason={context?.appointment_reason ?? appointment.reason} history={saved} completed={isCompleted} saving={saving} onSave={saveHistory} />
      <VitalSignsModule episodeId={appointment.id} historyId={saved?.id ?? null} vitalSigns={vitalSigns} completed={isCompleted} loading={loadingVitalSigns} onSaved={setVitalSigns} />
      <DiagnosesModule episodeId={appointment.id} historyId={saved?.id ?? null} diagnoses={diagnoses} completed={isCompleted} onChange={setDiagnoses} onError={setError} />
      <PrescriptionsModule episodeId={appointment.id} historyId={saved?.id ?? null} prescriptions={prescriptions} completed={isCompleted} onChange={setPrescriptions} onError={setError} downloadingPrescriptionPdf={downloadingPrescriptionPdf} downloadPrescriptionPdf={downloadPrescriptionPdf} />
      {saved ? <ClinicalOrdersSection historyId={saved.id} specialtyId={saved.specialty_id} completed={isCompleted} allowAdditional={Boolean(isCompleted && currentUser?.is_active && currentUser.roles.includes("doctor") && saved.doctor_id === currentUser.id)} /> : <div className="rounded-xl border border-dashed bg-white p-6 text-sm text-slate-600 shadow-sm">Guarda primero la consulta para crear órdenes estructuradas de laboratorio, estudios o procedimientos.</div>}
      <div className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">Estudios y análisis</h3><p className="text-sm text-slate-500">Solicitudes asociadas a esta consulta.</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs text-indigo-700">{requestedTests.length} solicitado{requestedTests.length === 1 ? "" : "s"}</span><button onClick={() => void downloadRequestedTestsPdf()} disabled={!requestedTests.length || downloadingTestsPdf} className="rounded-lg border border-indigo-300 px-3 py-2 text-sm font-medium text-indigo-700 disabled:opacity-40">{downloadingTestsPdf ? "Generando PDF..." : "Descargar orden PDF"}</button></div></div>{!saved && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Primero guarda la consulta para solicitar estudios o análisis.</p>}{!isCompleted && <>{studyCatalog.length > 0 && <div className="mt-4 rounded-lg border border-indigo-100 bg-indigo-50/60 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-indigo-700">Sugerencias de {specialtyName}</p><div className="mt-2 flex flex-wrap gap-2">{studyCatalog.map((study) => { const selected = requestedTests.some((item) => item.test_name.toLocaleLowerCase() === study.name.toLocaleLowerCase()); return <button key={study.id} onClick={() => void addRequestedTest(study.name)} disabled={!saved || savingRequestedTest || selected} className="rounded-full border border-indigo-200 bg-white px-3 py-1.5 text-sm text-indigo-800 disabled:bg-indigo-100 disabled:text-indigo-400">{selected ? "✓ " : "+ "}{study.name}</button>; })}</div></div>}<div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={requestedTest} onChange={(e) => setRequestedTest(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); void addRequestedTest(); } }} placeholder="Ej. Hemograma, ecocardiograma..." disabled={!saved} className="min-w-0 flex-1 rounded-lg border p-2.5 disabled:bg-slate-100" /><button onClick={() => void addRequestedTest()} disabled={!saved || savingRequestedTest || !requestedTest.trim()} className="rounded-lg bg-indigo-700 px-4 py-2.5 font-medium text-white disabled:opacity-50">{savingRequestedTest ? "Guardando..." : "Agregar estudio"}</button></div></>}<div className="mt-5 space-y-2">{requestedTests.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 rounded-lg bg-slate-50 p-3"><p className="font-medium">{item.test_name}</p>{!isCompleted && <button onClick={() => void removeRequestedTest(item.id)} className="text-sm font-medium text-red-600 hover:underline">Eliminar</button>}</div>)}{saved && !requestedTests.length && <p className="text-sm text-slate-500">No hay estudios ni análisis solicitados.</p>}</div></div>
    </div><aside className="space-y-4"><div className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Contexto de atención</h3><dl className="mt-3 space-y-3 text-sm"><div><dt className="text-slate-500">Paciente</dt><dd className="font-semibold">{appointment.patient_name}</dd></div><div><dt className="text-slate-500">Fecha de nacimiento</dt><dd className="font-semibold">{appointment.patient_date_of_birth}</dd></div><div><dt className="text-slate-500">Documento</dt><dd className="text-slate-500">No registrado en el modelo actual</dd></div><div><dt className="text-slate-500">Médico</dt><dd className="font-semibold">{appointment.doctor_name}</dd></div><div><dt className="text-slate-500">Centro</dt><dd className="font-semibold">{appointment.center_name ? `${appointment.center_name}${appointment.center_city ? ` · ${appointment.center_city}` : ""}` : "Sin centro"}</dd></div><div><dt className="text-slate-500">Motivo</dt><dd>{appointment.reason || "—"}</dd></div></dl><div className="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">appointment_id: <strong>{context?.appointment_id}</strong><br />doctor_id: <strong>{context?.doctor_id}</strong><br />center_id: <strong>{context?.center_id ?? "NULL"}</strong></div></div><div className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Consultas anteriores</h3>{previousConsultations.length ? <div className="mt-3 space-y-3">{previousConsultations.slice(0, 5).map((item) => <div key={item.id} className="rounded-lg bg-slate-50 p-3 text-sm"><p className="font-medium">{item.consultation_date}</p><p className="mt-1 text-slate-600">{item.reason_for_visit || "Sin motivo registrado"}</p><button onClick={() => void viewPrevious(item)} disabled={loadingPrevious} className="mt-2 font-medium text-teal-700 hover:underline disabled:opacity-40">{loadingPrevious ? "Cargando..." : "Ver historial completo"}</button></div>)}</div> : <p className="mt-3 text-sm text-slate-500">No hay consultas anteriores.</p>}</div></aside></div>
    {previousDetails && <PreviousConsultationModal details={previousDetails} onClose={() => setPreviousDetails(null)} onDownload={() => void downloadPreviousSummary(previousDetails.consultation.id)} />}
  </section>;
}

function PreviousConsultationModal({ details, onClose, onDownload }: { details: PreviousDetails; onClose: () => void; onDownload: () => void }) { const item = details.consultation; const vitals = details.vitalSigns; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-label="Historial clínico anterior"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-semibold">Consulta del {item.consultation_date}</h3><p className="text-sm text-slate-500">Historial anterior · solo lectura</p></div><button onClick={onClose} className="rounded border px-3 py-1.5 text-sm">Cerrar</button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><HistoryBlock title="Motivo e historia" lines={[item.reason_for_visit, item.current_illness, item.clinical_notes]} /><HistoryBlock title="Antecedentes" lines={[item.personal_history, item.family_history, item.allergies, item.chronic_conditions]} /><HistoryBlock title="Signos vitales" lines={vitals ? [`PA: ${vitals.systolic_pressure ?? "—"}/${vitals.diastolic_pressure ?? "—"} mmHg`, `FC: ${vitals.heart_rate ?? "—"} lpm · FR: ${vitals.respiratory_rate ?? "—"} rpm`, `Temperatura: ${vitals.temperature_c ?? "—"} °C · SpO₂: ${vitals.oxygen_saturation ?? "—"}%`, `Peso: ${vitals.weight_kg ?? "—"} kg · Talla: ${vitals.height_cm ?? "—"} cm`] : []} /><HistoryBlock title="Diagnósticos" lines={details.diagnoses.map((diagnosis) => `${diagnosis.is_primary ? "Principal · " : ""}${diagnosis.icd10_code ? `${diagnosis.icd10_code} · ` : ""}${diagnosis.description}`)} /><HistoryBlock title="Recetas" lines={details.prescriptions.map((prescription) => `${prescription.medication}${prescription.dose ? ` · ${prescription.dose}` : ""}${prescription.frequency ? ` · ${prescription.frequency}` : ""}`)} /><HistoryBlock title="Estudios" lines={details.requestedTests.map((test) => test.test_name)} /></div><button onClick={onDownload} className="mt-5 rounded-lg bg-teal-700 px-4 py-2 text-sm font-medium text-white">Descargar resumen PDF</button></div></div>; }
function HistoryBlock({ title, lines }: { title: string; lines: Array<string | null> }) { const visible = lines.filter((line): line is string => Boolean(line)); return <div className="rounded-lg bg-slate-50 p-4"><h4 className="font-semibold">{title}</h4>{visible.length ? <ul className="mt-2 space-y-1 text-sm text-slate-700">{visible.map((line, index) => <li key={`${title}-${index}`}>{line}</li>)}</ul> : <p className="mt-2 text-sm text-slate-500">Sin datos registrados.</p>}</div>; }

function Field({ label, value, disabled, onChange }: { label: string; value: string; disabled?: boolean; onChange: (value: string) => void }) { return <label className="text-sm font-medium">{label}<textarea value={value} disabled={disabled} onChange={(e) => onChange(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-2.5 disabled:bg-slate-100" /></label>; }
function VitalInput({ label, unit, value, disabled, min, max, step = "1", onChange }: { label: string; unit: string; value: string; disabled?: boolean; min: number; max: number; step?: string; onChange: (value: string) => void }) { return <label className="text-sm font-medium">{label}<div className="mt-1 flex overflow-hidden rounded-lg border bg-white focus-within:ring-2 focus-within:ring-cyan-200"><input type="number" inputMode="decimal" value={value} min={min} max={max} step={step} disabled={disabled} onChange={(e) => onChange(e.target.value)} className="min-w-0 flex-1 p-2.5 outline-none disabled:bg-slate-100" /><span className="flex items-center border-l bg-slate-50 px-2 text-xs text-slate-500">{unit}</span></div></label>; }
