import { useEffect, useState } from "react";

import { clinicalApi, clinicalErrorMessage } from "../../services/clinicalApi";
import type { VitalSignsInput } from "../../services/clinicalApi";
import type { VitalSigns } from "../../types/clinical";

type Form = Record<keyof VitalSignsInput, string>;
type Props = { episodeId: number; historyId: number | null; vitalSigns: VitalSigns | null; completed: boolean; loading: boolean; onSaved: (vitalSigns: VitalSigns) => void; onDirtyChange?: (dirty: boolean) => void };
const empty = (): Form => ({ systolic_pressure: "", diastolic_pressure: "", heart_rate: "", respiratory_rate: "", temperature_c: "", oxygen_saturation: "", weight_kg: "", height_cm: "" });
const fromVitalSigns = (value: VitalSigns | null): Form => value ? Object.fromEntries(Object.entries(value).filter(([key]) => key in empty()).map(([key, item]) => [key, item?.toString() || ""])) as Form : empty();

export default function VitalSignsModule({ episodeId, historyId, vitalSigns, completed, loading, onSaved, onDirtyChange }: Props) {
  const [form, setForm] = useState<Form>(() => fromVitalSigns(vitalSigns)); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(Boolean(vitalSigns));
  useEffect(() => { setForm(fromVitalSigns(vitalSigns)); setSaved(Boolean(vitalSigns)); setError(""); }, [episodeId, historyId, vitalSigns?.updated_at]);
  const dirty = JSON.stringify(form) !== JSON.stringify(fromVitalSigns(vitalSigns));
  useEffect(() => { onDirtyChange?.(dirty); }, [dirty, onDirtyChange]);
  const update = (field: keyof Form, value: string) => { setForm((current) => ({ ...current, [field]: value })); setSaved(false); };
  async function save() { if (!historyId || completed || loading || !Object.values(form).some((value) => value.trim())) return; setSaving(true); setError(""); try { const numberOrNull = (value: string) => value.trim() ? Number(value) : null; const payload: VitalSignsInput = Object.fromEntries(Object.entries(form).map(([key, value]) => [key, numberOrNull(value)])) as VitalSignsInput; const data = await clinicalApi.saveVitalSigns(historyId, payload); onSaved(data); setSaved(true); } catch (reason: unknown) { setError(clinicalErrorMessage(reason, "Revisa los rangos y la relación entre presión sistólica y diastólica.")); } finally { setSaving(false); } }
  const input = (label: string, unit: string, key: keyof Form, min: number, max: number, step = "1") => <label className="text-sm font-medium">{label}<div className="mt-1 flex overflow-hidden rounded-lg border bg-white focus-within:ring-2 focus-within:ring-cyan-200"><input type="number" inputMode="decimal" value={form[key]} min={min} max={max} step={step} disabled={!historyId || completed} onChange={(event) => update(key, event.target.value)} className="min-w-0 flex-1 p-2.5 outline-none disabled:bg-slate-100" /><span className="flex items-center border-l bg-slate-50 px-2 text-xs text-slate-500">{unit}</span></div></label>;
  return <div className="rounded-xl border bg-white p-4 shadow-sm sm:p-6" aria-busy={saving || loading}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">Signos vitales</h3><p className="text-sm text-slate-500">Mediciones asociadas exclusivamente a esta consulta.</p></div>{saved && !dirty && <span role="status" className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700">Guardados</span>}</div>{!historyId && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Primero guarda la consulta para registrar signos vitales.</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{input("Presión sistólica", "mmHg", "systolic_pressure", 40, 300)}{input("Presión diastólica", "mmHg", "diastolic_pressure", 20, 200)}{input("Frecuencia cardíaca", "lpm", "heart_rate", 20, 300)}{input("Frecuencia respiratoria", "rpm", "respiratory_rate", 5, 80)}{input("Temperatura", "°C", "temperature_c", 25, 45, "0.1")}{input("Saturación de oxígeno", "%", "oxygen_saturation", 0, 100, "0.01")}{input("Peso", "kg", "weight_kg", 1, 500, "0.01")}{input("Talla", "cm", "height_cm", 20, 300, "0.01")}</div>{error && <div role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{!completed && <div className="mt-4 flex justify-end"><button onClick={() => void save()} disabled={!historyId || saving || !dirty || !Object.values(form).some((value) => value.trim())} className="rounded-lg bg-cyan-700 px-4 py-2.5 font-medium text-white disabled:opacity-50">{saving ? "Guardando..." : saved ? "Actualizar signos vitales" : "Guardar signos vitales"}</button></div>}</div>;
}
